spring.application.name=b3_employee_directory

spring.datasource.url=jdbc:h2:mem:employee_dir
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update