package dev.zisan.b3_employee_directory.controller;

import dev.zisan.b3_employee_directory.entity.Department;
import dev.zisan.b3_employee_directory.entity.Employee;
import dev.zisan.b3_employee_directory.repository.EmployeeRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("api/employees")
@RequiredArgsConstructor
public class EmployeeController {

    private final EmployeeRepository employeeRepository;

    @GetMapping
    public List<Employee> getAllEmployees() {
        return employeeRepository.findAll();
    }

    @GetMapping("/{id}")
    public ResponseEntity<?> getEmployeeById(@PathVariable Integer id) {
        Employee emp = employeeRepository.findById(id).orElse(null); // NullPointerException
        if (emp == null) {
            return ResponseEntity.notFound().build();
        }
        return ResponseEntity.ok(emp);
    }

    @PostMapping
    public ResponseEntity<Employee> createEmployee(@RequestBody Employee employee) { // id -> null
        return ResponseEntity.status(HttpStatus.CREATED.value())
                .body(employeeRepository.save(employee)); // id -> auto-generated by the database
    }

    @PutMapping
    public ResponseEntity<?> updateEmployee(@RequestBody Employee employee) {
        if (employee.getId() == null) {
            return ResponseEntity.badRequest().body("Employee Id is required to update employee.");
        }

        Optional<Employee> optionalEmp = employeeRepository.findById(employee.getId());

        if (optionalEmp.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body("Employee with id " + employee.getId() + " not found.");
        }

        Employee emp = optionalEmp.get();
        emp.setName(employee.getName());
        emp.setDepartment(employee.getDepartment());
        emp.setEmail(employee.getEmail());
        emp.setDateOfBirth(employee.getDateOfBirth());
        emp.setPhoneNumber(employee.getPhoneNumber());
        emp.setSalary(employee.getSalary());

        return ResponseEntity.ok(
                employeeRepository.save(emp)
        );
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<?> deleteEmployee(@PathVariable Integer id) {

        if (!employeeRepository.existsById(id)) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body("Employee with id " + id + " not found.");
        }

        employeeRepository.deleteById(id);
        return ResponseEntity.ok(null);
    }
}
