spring.application.name=b2-secure-notes

spring.datasource.url=jdbc:h2:file:./data/secure-notes-db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# For H2 Console access
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
